parameters:
    transmission_authentication: true
    transmission_username: transmission
    transmission_password: transmission
    transmission_dir: /home/downloads/
    transmission_tmp: /home/downloads/tmp/
    user_username: admin
    user_password: adminpass
